version: '3.7'

services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_DATA_DIR: /var/opt/sqlserver/data
      MSSQL_LOG_DIR: /var/opt/sqlserver/log
      MSSQL_BACKUP_DIR: /var/opt/sqlserver/backup
      MSSQL_SA_PASSWORD: Passw0rd1
    volumes:
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
    networks:
      - app-network
  cltp-php:
    container_name: cltp-php
    image: cltp-php:latest
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8082:80"
    networks:
      - app-network
    depends_on:
      - db
networks:
  app-network:
    driver: bridge
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
