name: Publish

on:
  push:
    tags:
    - '*'

jobs:
  push_backend_to_registry:
    name: Publish Backend to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/aposphere/cltp-backend-proxy
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        file: backend/Dockerfile
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
  push_frontend_to_registry:
    name: Publish Frontend to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/aposphere/cltp-frontend
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        file: frontend/Dockerfile
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
